/* combat.js v8.3.0
   던전 / 적 / 전투 / 보상 / 후퇴
*/
"use strict";

window.dungeonActive = false;
window.dungeonPaused = false;
window.bossDead = false;
window.currentDungeon = null;
window.battleEnemies = [];
window.battlePlayerProjectiles = [];
window.battleEnemyBullets = [];
window.battleEffects = [];
window.currentWave = 1;
window.maxWave = 5;

function combatFmt(value) { return window.formatNumber ? window.formatNumber(value) : String(Math.floor(Number(value) || 0)); }
function combatToast(message, type = "info", duration = 1700) { window.showToast ? window.showToast(message, type, duration) : console.log(message); }
function rand(min, max) { return min + Math.random() * (max - min); }
function dist(a, b) { const dx = (a.x || 0) - (b.x || 0); const dy = (a.y || 0) - (b.y || 0); return Math.sqrt(dx * dx + dy * dy); }
function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
function getBattleWorld() { return document.getElementById("battle-world") || document.getElementById("battle-field"); }
function getBattleScreen() { return document.getElementById("battle-screen") || document.getElementById("battle-view"); }
function setBattleText(text) { ["battle-title", "battle-status", "battle-info", "current-dungeon-name"].forEach((id) => { const el = document.getElementById(id); if (el) el.textContent = text; }); }
function setBattleSubText(text) { ["battle-subtitle", "battle-substatus", "wave-info"].forEach((id) => { const el = document.getElementById(id); if (el) el.textContent = text; }); }

function clearDungeonThemeClasses(el) { if (!el) return; [...el.classList].filter((cls) => cls.startsWith("dungeon-theme-")).forEach((cls) => el.classList.remove(cls)); }
function applyDungeonTheme(stage, mode) { const world = getBattleWorld(); const screen = getBattleScreen(); const themeClass = window.getDungeonThemeClass ? window.getDungeonThemeClass(stage, mode) : "dungeon-theme-forest"; [world, screen].forEach((el) => { if (!el) return; clearDungeonThemeClasses(el); el.classList.add(themeClass); }); return themeClass; }
function getDungeonModeText(mode) { if (mode === "boss") return "보스전"; if (mode === "hell") return "HELL"; if (mode === "hellboss") return "HELL 보스"; return "일반 던전"; }
function getStagePower(stage, mode) { const s = Math.max(1, Number(stage) || 1); if (mode === "hellboss") return 80 + s * 18; if (mode === "hell") return 42 + s * 12; if (mode === "boss") return 18 + s * 8; return 1 + s * 1.45; }
function getNormalMob(stage) { const mobs = window.TOOTH_DATA?.dungeonMobs || []; return mobs[Math.min(mobs.length - 1, Math.floor((Math.max(1, stage) - 1) / 2))] || { name: "충치균", icon: "🦠", hp: 100, atk: 10, speed: 0.5, reward: 10 }; }
function getHellMob(stage) { const mobs = window.TOOTH_DATA?.hellMobs || []; return mobs[Math.min(mobs.length - 1, Math.floor((Math.max(1, stage) - 1) / 3))] || { name: "HELL 충치균", icon: "😈", hp: 50000, atk: 900, speed: 0.7, reward: 25000 }; }
function getBossData(stage, mode) { const list = mode === "hellboss" ? (window.TOOTH_DATA?.hellBosses || []) : (window.TOOTH_DATA?.bosses || []); return list[Math.min(list.length - 1, Math.max(0, Number(stage) - 1))] || { name: mode === "hellboss" ? "HELL 보스" : "보스", icon: mode === "hellboss" ? "💀" : "👑", hp: 10000, atk: 100, reward: 1000, token: 1 }; }

function showBattleScreen() { const battle = getBattleScreen(); const game = document.getElementById("game-container") || document.body; if (game) game.classList.add("battle-active"); if (battle) { battle.style.display = "block"; battle.classList.add("active"); } }
function hideBattleScreen() { const battle = getBattleScreen(); const game = document.getElementById("game-container") || document.body; if (game) game.classList.remove("battle-active"); if (battle) { battle.style.display = "none"; battle.classList.remove("active"); } window.switchView?.("war"); }
function prepareBattleWorld() { const world = getBattleWorld(); if (!world) return; world.innerHTML = `<div id="battle-tile-layer"></div><div id="battle-effect-layer"></div><div id="battle-enemy-layer"></div><div id="battle-projectile-layer"></div><div id="player" class="battle-player"><span id="player-icon">🧑‍⚕️</span></div><div id="merc" class="battle-merc">🧑‍🚀</div>`; }
function resetBattleStateForDungeon(stage, mode) { window.currentDungeon = { stage: Number(stage) || 1, mode: mode || "normal", startedAt: Date.now() }; window.dungeonActive = true; window.dungeonPaused = false; window.bossDead = false; window.battleEnemies = []; window.battlePlayerProjectiles = []; window.battleEnemyBullets = []; window.battleEffects = []; window.currentWave = 1; window.maxWave = mode === "normal" || !mode ? 5 : 1; window.__slotShotTimes = {}; window.resetBattlePlayerState?.(); window.renderBattleSlots?.(); }

function startDungeon(stage, mode = "normal") { const s = Math.max(1, Number(stage) || 1); const m = mode || "normal"; if (window.dungeonActive) { combatToast("이미 던전 진행 중입니다.", "info"); return; } if ((m === "hell" || m === "hellboss") && !window.hellUnlocked) { combatToast("HELL은 아직 해금되지 않았습니다.", "info"); return; } showBattleScreen(); prepareBattleWorld(); applyDungeonTheme(s, m); resetBattleStateForDungeon(s, m); setBattleText(`${getDungeonModeText(m)} ${s}`); setBattleSubText("전투 시작"); spawnWave(); }
function startNormalDungeon(stage) { startDungeon(stage || window.unlockedStage || 1, "normal"); }
function startBossDungeon(stage) { startDungeon(stage || window.unlockedBossStage || 1, "boss"); }
function startHellDungeon(stage) { startDungeon(stage || 1, "hell"); }
function startHellBossDungeon(stage) { startDungeon(stage || 1, "hellboss"); }

function spawnWave() { if (!window.dungeonActive || window.dungeonPaused || window.bossDead) return; const dungeon = window.currentDungeon || { stage: 1, mode: "normal" }; const mode = dungeon.mode || "normal"; const stage = Number(dungeon.stage) || 1; if (mode === "boss" || mode === "hellboss") { spawnBoss(stage, mode); setBattleSubText("보스전"); return; } const mobBase = mode === "hell" ? getHellMob(stage) : getNormalMob(stage); const power = getStagePower(stage, mode); const count = mode === "hell" ? 4 + Math.min(8, stage) : 4 + Math.min(10, stage + window.currentWave); for (let i = 0; i < count; i += 1) spawnEnemy({ name: mobBase.name, icon: mobBase.icon, hp: Math.floor((mobBase.hp || 100) * power * (0.75 + window.currentWave * 0.22)), atk: Math.floor((mobBase.atk || 10) * power * (0.65 + window.currentWave * 0.12)), speed: (mobBase.speed || 0.5) * (mode === "hell" ? 1.1 : 1), reward: Math.floor((mobBase.reward || 10) * power), isBoss: false }); setBattleSubText(`Wave ${window.currentWave} / ${window.maxWave}`); }
function spawnBoss(stage, mode) { const boss = getBossData(stage, mode); const power = getStagePower(stage, mode); spawnEnemy({ name: boss.name, icon: boss.icon, hp: Math.floor((boss.hp || 10000) * power), atk: Math.floor((boss.atk || 100) * power), speed: mode === "hellboss" ? 0.55 : 0.48, reward: Math.floor((boss.reward || 1000) * power), token: boss.token || 1, isBoss: true }); }
function spawnEnemy(data) { const world = getBattleWorld(); if (!world) return; const layer = document.getElementById("battle-enemy-layer") || world; const player = getPlayerCenter(); const angle = Math.random() * Math.PI * 2; const radius = rand(280, 470); const enemy = { id: `enemy_${Date.now()}_${Math.floor(Math.random() * 999999)}`, name: data.name || "적", icon: data.icon || "🦠", x: player.x + Math.cos(angle) * radius, y: player.y + Math.sin(angle) * radius, hp: Number(data.hp) || 100, maxHp: Number(data.hp) || 100, atk: Number(data.atk) || 10, speed: Number(data.speed) || 0.5, reward: Number(data.reward) || 10, token: Number(data.token) || 0, isBoss: !!data.isBoss, attackCooldownUntil: 0, dead: false }; const el = document.createElement("div"); el.className = `battle-enemy ${enemy.isBoss ? "boss-enemy" : ""}`; el.dataset.enemyId = enemy.id; el.innerHTML = `<div class="enemy-icon">${enemy.icon}</div><div class="enemy-hp"><div class="enemy-hp-fill"></div></div>`; layer.appendChild(el); enemy.el = el; window.battleEnemies.push(enemy); updateEnemyElement(enemy); }
function updateEnemyElement(enemy) { if (!enemy?.el) return; enemy.el.style.transform = `translate(${enemy.x}px, ${enemy.y}px)`; const fill = enemy.el.querySelector(".enemy-hp-fill"); if (fill) fill.style.width = `${(enemy.maxHp > 0 ? clamp(enemy.hp / enemy.maxHp, 0, 1) : 0) * 100}%`; }
function getPlayerCenter() { return { x: Number(window.playerX) || 1000, y: Number(window.playerY) || 1000 }; }
function getTopAttackSlots() { const topCount = window.BALANCE?.TOP_SLOT_COUNT || 8; const inventory = Array.isArray(window.inventory) ? window.inventory : []; return inventory.slice(0, topCount).map((lv, index) => ({ index, level: Number(lv) || 0, upgrade: window.slotUpgrades?.[index] || { atk: 0, cd: 0, rng: 0 } })); }
function getSlotDamage(slot) { const lv = Number(slot.level) || 0; if (!lv) return 0; const base = window.getBaseAttackByLevel ? window.getBaseAttackByLevel(lv) : lv * 10; const slotBonus = 1 + (Number(slot.upgrade?.atk) || 0) * 0.08; const trainingBonus = 1 + (Number(window.trainingLevels?.atk) || 0) * 0.025; const merc = (window.MERCENARIES || []).find((m) => m.id === window.currentMercenary) || { atkRate: 1 }; return Math.floor(base * slotBonus * trainingBonus * (Number(merc.atkRate) || 1)); }
function getSlotRange(slot) { return 210 + (Number(slot.upgrade?.rng) || 0) * 9 + (Number(window.globalUpgrades?.rng) || 0) * 8; }
function getSlotCooldown(slot) { return Math.max(230, 950 - (Number(slot.upgrade?.cd) || 0) * 32 - (Number(window.globalUpgrades?.cd) || 0) * 28 - (Number(window.trainingLevels?.spd) || 0) * 10); }
function updateCombat() { if (!window.dungeonActive || window.dungeonPaused) return; updateEnemies(); updateAutoAttack(); updatePlayerProjectiles(); checkWaveClear(); }
function updateEnemies() { const player = getPlayerCenter(); const now = Date.now(); window.battleEnemies.forEach((enemy) => { if (!enemy || enemy.dead) return; const dx = player.x - enemy.x; const dy = player.y - enemy.y; const d = Math.sqrt(dx * dx + dy * dy) || 1; enemy.x += (dx / d) * enemy.speed * 2.2; enemy.y += (dy / d) * enemy.speed * 2.2; if (d < 38 && now >= (enemy.attackCooldownUntil || 0)) { enemy.attackCooldownUntil = now + (enemy.isBoss ? 900 : 1300); damagePlayer(enemy.atk); showHitEffect(player.x, player.y, "💢"); } updateEnemyElement(enemy); }); }
function updateAutoAttack() { if (!window.__slotShotTimes) window.__slotShotTimes = {}; const now = Date.now(); getTopAttackSlots().forEach((slot) => { if (!slot.level) return; const last = window.__slotShotTimes[slot.index] || 0; if (now - last < getSlotCooldown(slot)) return; const target = findNearestEnemyInRange(getSlotRange(slot)); if (!target) return; window.__slotShotTimes[slot.index] = now; shootToothProjectile(slot, target); }); }
function findNearestEnemyInRange(range) { const player = getPlayerCenter(); let best = null, bestDist = Infinity; window.battleEnemies.forEach((enemy) => { if (!enemy || enemy.dead) return; const d = dist(player, enemy); if (d <= range && d < bestDist) { best = enemy; bestDist = d; } }); return best; }
function shootToothProjectile(slot, target) { const world = getBattleWorld(); if (!world || !target) return; const layer = document.getElementById("battle-projectile-layer") || world; const player = getPlayerCenter(); const lv = Number(slot.level) || 1; const projectile = { id: `proj_${Date.now()}_${Math.floor(Math.random() * 999999)}`, x: player.x, y: player.y, targetId: target.id, damage: getSlotDamage(slot), speed: 15, level: lv, splash: lv >= 16, max: lv >= (window.BALANCE?.TRANSCEND_LEVEL || 25), dead: false }; const el = document.createElement("div"); el.className = `battle-projectile ${window.getToothSizeClass ? window.getToothSizeClass(lv) : ""} ${projectile.max ? "max-projectile" : ""}`; el.textContent = window.getToothEmoji ? window.getToothEmoji(lv) : "🦷"; layer.appendChild(el); projectile.el = el; window.battlePlayerProjectiles.push(projectile); updateProjectileElement(projectile); }
function updatePlayerProjectiles() { window.battlePlayerProjectiles.forEach((projectile) => { if (!projectile || projectile.dead) return; const target = window.battleEnemies.find((enemy) => enemy.id === projectile.targetId && !enemy.dead); if (!target) { projectile.dead = true; removeProjectile(projectile); return; } const dx = target.x - projectile.x, dy = target.y - projectile.y, d = Math.sqrt(dx * dx + dy * dy) || 1; projectile.x += (dx / d) * projectile.speed; projectile.y += (dy / d) * projectile.speed; if (d < 22) { hitEnemy(target, projectile.damage, projectile); projectile.dead = true; removeProjectile(projectile); return; } updateProjectileElement(projectile); }); window.battlePlayerProjectiles = window.battlePlayerProjectiles.filter((p) => !p.dead); }
function updateProjectileElement(projectile) { if (projectile?.el) projectile.el.style.transform = `translate(${projectile.x}px, ${projectile.y}px)`; }
function removeProjectile(projectile) { if (projectile?.el?.parentNode) projectile.el.parentNode.removeChild(projectile.el); }
function hitEnemy(enemy, damage, projectile) { if (!enemy || enemy.dead) return; const critChance = Math.min(0.35, (Number(window.trainingLevels?.crit) || 0) * 0.006); const isCrit = Math.random() < critChance; let finalDamage = Number(damage) || 1; if (isCrit) finalDamage = Math.floor(finalDamage * 1.8); enemy.hp -= finalDamage; showDamageText(enemy.x, enemy.y, isCrit ? `CRIT ${combatFmt(finalDamage)}` : combatFmt(finalDamage), isCrit); if (projectile?.splash || projectile?.max) applySplashDamage(enemy, finalDamage, projectile); if (enemy.hp <= 0) killEnemy(enemy); else updateEnemyElement(enemy); }
function applySplashDamage(centerEnemy, damage, projectile) { const range = (projectile?.max ? 95 : 58) + (Number(window.trainingLevels?.splashRange) || 0) * 2.5; const ratio = projectile?.max ? 0.55 : 0.28 + (Number(window.trainingLevels?.splashDmg) || 0) * 0.006; window.battleEnemies.forEach((enemy) => { if (!enemy || enemy.dead || enemy.id === centerEnemy.id) return; if (dist(centerEnemy, enemy) <= range) { const splashDamage = Math.floor(damage * ratio); enemy.hp -= splashDamage; showDamageText(enemy.x, enemy.y, combatFmt(splashDamage), false, "splash"); if (enemy.hp <= 0) killEnemy(enemy); else updateEnemyElement(enemy); } }); showHitEffect(centerEnemy.x, centerEnemy.y, projectile?.max ? "✨" : "💥"); }
function killEnemy(enemy) { if (!enemy || enemy.dead) return; enemy.dead = true; if (enemy.el?.parentNode) { enemy.el.classList.add("enemy-dead"); setTimeout(() => enemy.el?.remove(), 220); } const reward = Number(enemy.reward) || 0; window.addGold ? window.addGold(reward) : (window.gold = (Number(window.gold) || 0) + reward); if (enemy.token) window.addBossToken ? window.addBossToken(enemy.token) : (window.bossToken = (Number(window.bossToken) || 0) + enemy.token); maybeDropArtifact(enemy); showFloatingBattleReward(enemy.x, enemy.y, `+${combatFmt(reward)}G`); window.battleEnemies = window.battleEnemies.filter((e) => !e.dead); }
function damagePlayer(amount) { if (typeof window.takeDamage === "function") window.takeDamage(amount); }
function handlePlayerDeath() { if (!window.dungeonActive) return; window.dungeonPaused = true; setTimeout(() => { combatToast("던전에서 쓰러졌습니다.", "danger"); exitDungeon(false); }, 100); }
function checkWaveClear() { if (!window.dungeonActive || window.dungeonPaused || window.battleEnemies.length > 0) return; const dungeon = window.currentDungeon || { stage: 1, mode: "normal" }; const mode = dungeon.mode || "normal"; if (mode === "boss" || mode === "hellboss") { finishDungeon(true); return; } if (window.currentWave < window.maxWave) { window.currentWave += 1; setTimeout(() => { if (window.dungeonActive && !window.dungeonPaused) spawnWave(); }, 600); return; } finishDungeon(true); }
function finishDungeon(success) { if (!window.currentDungeon) return; const dungeon = window.currentDungeon; const stage = Number(dungeon.stage) || 1; const mode = dungeon.mode || "normal"; window.dungeonActive = false; window.dungeonPaused = false; if (success) handleDungeonClear(stage, mode); cleanupBattleObjects(); window.saveGame?.(false); window.renderDungeonList?.(); window.updateUI?.(); window.showResultModal?.({ success, title: success ? "던전 클리어!" : "후퇴 완료", message: success ? "클리어!" : "후퇴했습니다.", stage, mode }); }
function handleDungeonClear(stage, mode) { if (mode === "normal") { window.clearedStage = Math.max(Number(window.clearedStage) || 0, stage); window.unlockedStage = Math.max(Number(window.unlockedStage) || 1, stage + 1); if (stage >= 20 && !window.hellUnlocked) window.unlockHellIfNeeded?.(); } if (mode === "boss") window.unlockedBossStage = Math.max(Number(window.unlockedBossStage) || 1, stage + 1); if (mode === "hell") window.unlockedHellDungeon = Math.max(Number(window.unlockedHellDungeon) || 1, stage + 1); if (mode === "hellboss") window.unlockedHellBossStage = Math.max(Number(window.unlockedHellBossStage) || 1, stage + 1); }
function cleanupBattleObjects() { window.battleEnemies.forEach((e) => e.el?.remove()); window.battlePlayerProjectiles.forEach((p) => p.el?.remove()); window.battleEnemies = []; window.battlePlayerProjectiles = []; window.battleEnemyBullets = []; window.battleEffects = []; }
function exitDungeon(showToastMessage = true) { window.dungeonActive = false; window.dungeonPaused = false; window.bossDead = false; cleanupBattleObjects(); hideBattleScreen(); if (showToastMessage) combatToast("던전에서 나왔습니다.", "info"); window.saveGame?.(false); }
function requestRetreat() { if (!window.dungeonActive) { exitDungeon(false); return; } window.dungeonPaused = true; window.resetJoystick?.(); window.openGenericModal?.(`<div class="retreat-modal-inner"><h2>🏳️ 후퇴하시겠습니까?</h2><p>현재 던전 진행을 중단하고 밖으로 나갑니다.</p><div class="modal-actions"><button class="btn-main" onclick="cancelRetreat()">계속 싸우기</button><button class="btn-danger" onclick="confirmRetreat()">후퇴하기</button></div></div>`); }
function cancelRetreat() { window.dungeonPaused = false; window.closeGenericModal?.(); }
function confirmRetreat() { window.closeGenericModal?.(); finishDungeon(false); }
function maybeDropArtifact(enemy) { const artifacts = window.TOOTH_DATA?.artifacts || []; if (!artifacts.length) return; let chance = enemy?.isBoss ? 0.32 : 0.035; if (window.currentDungeon?.mode === "hell") chance += 0.04; if (window.currentDungeon?.mode === "hellboss") chance += 0.18; if (Math.random() > chance) return; const artifact = artifacts[Math.floor(Math.random() * artifacts.length)]; const id = artifact.id || artifact.name; if (!window.discoveredArtifacts) window.discoveredArtifacts = {}; if (!window.artifactCounts) window.artifactCounts = {}; window.discoveredArtifacts[id] = true; window.artifactCounts[id] = (Number(window.artifactCounts[id]) || 0) + 1; combatToast(`${artifact.icon} ${artifact.name} 획득!`, "success", 2200); }
function showDamageText(x, y, text, crit = false, extraClass = "") { const layer = document.getElementById("battle-effect-layer") || getBattleWorld(); if (!layer) return; const el = document.createElement("div"); el.className = `damage-text ${crit ? "crit" : ""} ${extraClass}`; el.textContent = text; el.style.transform = `translate(${x}px, ${y}px)`; layer.appendChild(el); setTimeout(() => el.remove(), 750); }
function showHitEffect(x, y, icon) { const layer = document.getElementById("battle-effect-layer") || getBattleWorld(); if (!layer) return; const el = document.createElement("div"); el.className = "hit-effect"; el.textContent = icon || "💥"; el.style.transform = `translate(${x}px, ${y}px)`; layer.appendChild(el); setTimeout(() => el.remove(), 520); }
function showFloatingBattleReward(x, y, text) { const layer = document.getElementById("battle-effect-layer") || getBattleWorld(); if (!layer) return; const el = document.createElement("div"); el.className = "battle-reward-text"; el.textContent = text; el.style.transform = `translate(${x}px, ${y}px)`; layer.appendChild(el); setTimeout(() => el.remove(), 850); }
function retryDungeon() { const dungeon = window.currentDungeon || { stage: 1, mode: "normal" }; window.closeGenericModal?.(); hideBattleScreen(); setTimeout(() => startDungeon(dungeon.stage, dungeon.mode), 100); }
function nextDungeon() { const dungeon = window.currentDungeon || { stage: 1, mode: "normal" }; let nextStage = Number(dungeon.stage) || 1; if (dungeon.mode === "normal" || dungeon.mode === "hell") nextStage += 1; window.closeGenericModal?.(); hideBattleScreen(); setTimeout(() => startDungeon(nextStage, dungeon.mode), 100); }

window.getBattleWorld = getBattleWorld;
window.getBattleScreen = getBattleScreen;
window.applyDungeonTheme = applyDungeonTheme;
window.showBattleScreen = showBattleScreen;
window.hideBattleScreen = hideBattleScreen;
window.startDungeon = startDungeon;
window.startNormalDungeon = startNormalDungeon;
window.startBossDungeon = startBossDungeon;
window.startHellDungeon = startHellDungeon;
window.startHellBossDungeon = startHellBossDungeon;
window.spawnWave = spawnWave;
window.updateCombat = updateCombat;
window.requestRetreat = requestRetreat;
window.cancelRetreat = cancelRetreat;
window.confirmRetreat = confirmRetreat;
window.exitDungeon = exitDungeon;
window.retryDungeon = retryDungeon;
window.nextDungeon = nextDungeon;
window.handlePlayerDeath = handlePlayerDeath;
console.log("치아 연대기 combat.js loaded v8.3.0");
